import { Pays } from "../../shared/models/pays.models";


export const PAYS_MOCK: Pays[] = [
  // ===== EUROPE =====
  { country: 'France', total: 0, url_image: 'images/france.jpg' },
  { country: 'Germany', total: 0, url_image: 'images/uk.jpg' },
  { country: 'Italy', total: 0, url_image: 'images/italy.jpg' },
  { country: 'Spain', total: 0, url_image: 'images/spain.jpg' },
  { country: 'Belgium', total: 0, url_image: 'images/belgium.jpg' },
  { country: 'Netherlands', total: 0, url_image: 'images/netherlands.jpg' },
  { country: 'Switzerland', total: 0, url_image: 'images/switzerland.jpg' },
  { country: 'Sweden', total: 0, url_image: 'images/sweden.jpg' },
  { country: 'Norway', total: 0, url_image: 'images/norway.jpg' },
  { country: 'Hungary', total: 0, url_image: 'images/hungary.jpg' },
  { country: 'Poland', total: 0, url_image: 'images/poland.jpg' },
  { country: 'Turkey', total: 0, url_image: 'images/turkey.jpg' },
  { country: 'Russia', total: 0, url_image: 'images/russia.jpg' },

  { country: 'Albania', total: 0, url_image: 'images/albania.jpg' },
  { country: 'Andorra', total: 0, url_image: 'images/andorra.jpg' },
  { country: 'Austria', total: 0, url_image: 'images/austria.jpg' },
  { country: 'Belarus', total: 0, url_image: 'images/belarus.jpg' },
  { country: 'Bosnia and Herzegovina', total: 0, url_image: 'images/bosnia-and-herzegovina.jpg' },
  { country: 'Bulgaria', total: 0, url_image: 'images/bulgaria.jpg' },
  { country: 'Croatia', total: 0, url_image: 'images/croatia.jpg' },
  { country: 'Denmark', total: 0, url_image: 'images/denmark.jpg' },
  { country: 'Estonia', total: 0, url_image: 'images/estonia.jpg' },
  { country: 'Finland', total: 0, url_image: 'images/finland.jpg' },
  { country: 'Greece', total: 0, url_image: 'images/greece.jpg' },
  { country: 'Ireland', total: 0, url_image: 'images/ireland.jpg' },
  { country: 'Iceland', total: 0, url_image: 'images/iceland.jpg' },
  { country: 'Luxembourg', total: 0, url_image: 'images/luxembourg.jpg' },
  { country: 'Portugal', total: 0, url_image: 'images/portugal.jpg' },
  { country: 'Czech Republic', total: 0, url_image: 'images/czech-republic.jpg' },
  { country: 'Romania', total: 0, url_image: 'images/romania.jpg' },
  { country: 'Serbia', total: 0, url_image: 'images/serbia.jpg' },
  { country: 'Slovakia', total: 0, url_image: 'images/slovakia.jpg' },
  { country: 'Slovenia', total: 0, url_image: 'images/slovenia.jpg' },
  { country: 'Ukraine', total: 0, url_image: 'images/ukraine.jpg' },

  // ===== ASIE =====
  { country: 'China', total: 0, url_image: 'images/china.jpg' },
  { country: 'Japan', total: 0, url_image: 'images/japan.jpg' },
  { country: 'South Korea', total: 0, url_image: 'images/south-korea.jpg' },
  { country: 'India', total: 0, url_image: 'images/india.jpg' },
  { country: 'Malaysia', total: 0, url_image: 'images/malaysia.jpg' },
  { country: 'United Arab Emirates', total: 0, url_image: 'images/uae.jpg' },
  { country: 'Morocco', total: 0, url_image: 'images/morocco.jpg' },
  { country: 'Tunisia', total: 0, url_image: 'images/tunisia.jpg' },
  { country: 'Saudi Arabia', total: 0, url_image: 'images/saudi-arabia.jpg' },
  { country: 'Israel', total: 0, url_image: 'images/israel.jpg' },

  { country: 'Afghanistan', total: 0, url_image: 'images/afghanistan.jpg' },
  { country: 'Bangladesh', total: 0, url_image: 'images/bangladesh.jpg' },
  { country: 'Bhutan', total: 0, url_image: 'images/bhutan.jpg' },
  { country: 'Cambodia', total: 0, url_image: 'images/cambodia.jpg' },
  { country: 'Indonesia', total: 0, url_image: 'images/indonesia.jpg' },
  { country: 'Iran', total: 0, url_image: 'images/iran.jpg' },
  { country: 'Iraq', total: 0, url_image: 'images/iraq.jpg' },
  { country: 'Jordan', total: 0, url_image: 'images/jordan.jpg' },
  { country: 'Kazakhstan', total: 0, url_image: 'images/kazakhstan.jpg' },
  { country: 'Qatar', total: 0, url_image: 'images/qatar.jpg' },
  { country: 'Singapore', total: 0, url_image: 'images/singapore.jpg' },
  { country: 'Thailand', total: 0, url_image: 'images/thailand.jpg' },
  { country: 'Vietnam', total: 0, url_image: 'images/vietnam.jpg' },

  // ===== AFRIQUE =====
  { country: 'South Africa', total: 0, url_image: 'images/south-africa.jpg' },
  { country: 'Algeria', total: 0, url_image: 'images/algeria.jpg' },
  { country: 'Angola', total: 0, url_image: 'images/angola.jpg' },
  { country: 'Benin', total: 0, url_image: 'images/benin.jpg' },
  { country: 'Botswana', total: 0, url_image: 'images/botswana.jpg' },
  { country: 'Burkina Faso', total: 0, url_image: 'images/burkina-faso.jpg' },
  { country: 'Burundi', total: 0, url_image: 'images/burundi.jpg' },
  { country: 'Cameroun', total: 0, url_image: 'images/cameroon.jpg' },
  { country: 'Cap-Vert', total: 0, url_image: 'images/cape-verde.jpg' },
  { country: 'Centrafrique', total: 0, url_image: 'images/central-african-republic.jpg' },
  { country: 'Comores', total: 0, url_image: 'images/comoros.jpg' },
  { country: 'Congo', total: 0, url_image: 'images/congo.jpg' },
  { country: 'Ivoir Coast', total: 0, url_image: 'images/ivory-coast.jpg' },
  { country: 'Egypt', total: 0, url_image: 'images/egypt.jpg' },
  { country: 'Ethiopia', total: 0, url_image: 'images/ethiopia.jpg' },
  { country: 'Gabon', total: 0, url_image: 'images/gabon.jpg' },
  { country: 'Ghana', total: 0, url_image: 'images/ghana.jpg' },
  { country: 'Guinee', total: 0, url_image: 'images/guinea.jpg' },
  { country: 'Kenya', total: 0, url_image: 'images/kenya.jpg' },
  { country: 'Madagascar', total: 0, url_image: 'images/madagascar.jpg' },
  { country: 'Mali', total: 0, url_image: 'images/mali.jpg' },
  { country: 'Maurice', total: 0, url_image: 'images/mauritius.jpg' },
  { country: 'Mozambique', total: 0, url_image: 'images/mozambique.jpg' },
  { country: 'Niger', total: 0, url_image: 'images/niger.jpg' },
  { country: 'Nigeria', total: 0, url_image: 'images/nigeria.jpg' },
  { country: 'Rwanda', total: 0, url_image: 'images/rwanda.jpg' },
  { country: 'Senegal', total: 0, url_image: 'images/senegal.jpg' },
  { country: 'Tanzania', total: 0, url_image: 'images/tanzania.jpg' },
  { country: 'Togo', total: 0, url_image: 'images/togo.jpg' },
  { country: 'Uganda', total: 0, url_image: 'images/uganda.jpg' },
  { country: 'Zambia', total: 0, url_image: 'images/zambia.jpg' },
  { country: 'Zimbabwe', total: 0, url_image: 'images/zimbabwe.jpg' },

  // ===== AMÉRIQUE =====
  { country: 'United States', total: 0, url_image: 'images/usa.jpg' },
  { country: 'Canada', total: 0, url_image: 'images/canada.jpg' },
  { country: 'Brazil', total: 0, url_image: 'images/brazil.jpg' },
  { country: 'Mexico', total: 0, url_image: 'images/mexico.jpg' },
  { country: 'Argentina', total: 0, url_image: 'images/argentina.jpg' },
  { country: 'Chile', total: 0, url_image: 'images/chile.jpg' },

  { country: 'Bolivia', total: 0, url_image: 'images/bolivia.jpg' },
  { country: 'Colombia', total: 0, url_image: 'images/colombia.jpg' },
  { country: 'Costa Rica', total: 0, url_image: 'images/costa-rica.jpg' },
  { country: 'Cuba', total: 0, url_image: 'images/cuba.jpg' },
  { country: 'Ecuador', total: 0, url_image: 'images/ecuador.jpg' },
  { country: 'Guatemala', total: 0, url_image: 'images/guatemala.jpg' },
  { country: 'Haiti', total: 0, url_image: 'images/haiti.jpg' },
  { country: 'Jamaica', total: 0, url_image: 'images/jamaica.jpg' },
  { country: 'Panama', total: 0, url_image: 'images/panama.jpg' },
  { country: 'Paraguay', total: 0, url_image: 'images/paraguay.jpg' },
  { country: 'Peru', total: 0, url_image: 'images/peru.jpg' },
  { country: 'Uruguay', total: 0, url_image: 'images/uruguay.jpg' },
  { country: 'Venezuela', total: 0, url_image: 'images/venezuela.jpg' },

  // ===== OCÉANIE =====
  { country: 'Australia', total: 0, url_image: 'images/australia.jpg' },
  { country: 'New Zealand', total: 0, url_image: 'images/new-zealand.jpg' },
  { country: 'Fiji', total: 0, url_image: 'images/fiji.jpg' },
  { country: 'Papua New Guinea', total: 0, url_image: 'images/papua-new-guinea.jpg' }
];